services:
  db:
    image: postgres:latest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wallet_api
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: wallet_api_production
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://wallet_api:${DB_PASSWORD}@db:5432/wallet_api_production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - db

volumes:
  postgres_dev_data:
