services:
  db:
    image: postgres:latest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wallet_api
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: wallet_api_production
    ports:
      - "5432:5432"

  bank_api:
    build:
      context: ./bank-api
    environment:
      PORT: 3000

  api:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://wallet_api:${DB_PASSWORD}@db:5432/wallet_api_production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      BANK_API_URL: http://bank_api:3000
      WEB_CONCURRENCY: 2
      RAILS_MAX_THREADS: 5
    ports:
      - "80:80"
    depends_on:
      - db
      - bank_api
    mem_limit: 1024m
    cpus: 2.00

volumes:
  postgres_dev_data:
