services:
  db_dev:
    image: postgres:latest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wallet_api_development
    ports:
      - "5432:5432"

  db_test:
    image: postgres:latest
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wallet_api_test
    ports:
      - "5433:5432"


volumes:
  postgres_dev_data:
  postgres_test_data: