#!/bin/bash

echo "*********************************************************"
echo "Running Rubocop auto-correction... "
echo "*********************************************************"

# Change to the root directory of the project
# shellcheck disable=SC2164
cd "$(dirname "$0")/.."

# Run Rubocop with auto-correction
bundle exec rubocop -A
status=$?

if [ "$status" -ne 0 ]; then
    echo "*********************************************************"
    echo "       ********************************************      "
    echo 1>&2 "Rubocop found issues it could not fix."
    echo "Run 'bundle exec rubocop' in your terminal and fix the issues before trying to commit again."
    echo "       ********************************************      "
    echo "*********************************************************"
    exit 1
fi

# Add all changes to the staging area
echo "*********************************************************"
echo "Adding all changes to the staging area... "
echo "*********************************************************"

git add .

# Exit
exit 0